package com.systemjaade.components;

import com.systemjaade.components.notify.core.Notification;

/**
 *
 * @author Tarazona Marrujo Elí Gamaliel - "System JAADE S.A.C."
 */
public class TestComponents extends javax.swing.JFrame {

  /**
   * Creates new form TestComponents
   */
  public TestComponents() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnTestNotification = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    btnTestNotification1 = new javax.swing.JButton();
    btnTestNotification2 = new javax.swing.JButton();
    btnTestNotification3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnTestNotification.setText("Info Notification");
    btnTestNotification.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTestNotificationActionPerformed(evt);
      }
    });

    jButton1.setBackground(new java.awt.Color(255, 51, 51));
    jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Close");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    btnTestNotification1.setText("Confirm Notification Light");
    btnTestNotification1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTestNotification1ActionPerformed(evt);
      }
    });

    btnTestNotification2.setText("Confirm Notification Grey");
    btnTestNotification2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTestNotification2ActionPerformed(evt);
      }
    });

    btnTestNotification3.setText("Confirm Notification Blue");
    btnTestNotification3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTestNotification3ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(29, 29, 29))
      .addGroup(layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnTestNotification3)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnTestNotification1)
              .addComponent(btnTestNotification)
              .addComponent(btnTestNotification2))
            .addGap(133, 414, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(btnTestNotification)
        .addGap(18, 18, 18)
        .addComponent(btnTestNotification2)
        .addGap(18, 18, 18)
        .addComponent(btnTestNotification1)
        .addGap(18, 18, 18)
        .addComponent(btnTestNotification3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(25, 25, 25))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnTestNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestNotificationActionPerformed
    Notification.show(Notification.SUPERIOR_DERECHO, "System JAADE SAC", "soy un mensaje", Notification.DARK_THEME, (short) 74, true, 1500);
  }//GEN-LAST:event_btnTestNotificationActionPerformed

  private void btnTestNotification1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestNotification1ActionPerformed
    Notification.showConfirm(Notification.SUPERIOR_DERECHO, "System JAADE SAC", "soy un mensaje", Notification.GRAY_THEME, (short) 73, true, 1500);
  }//GEN-LAST:event_btnTestNotification1ActionPerformed

  private void btnTestNotification2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestNotification2ActionPerformed
    Notification.showConfirm(Notification.SUPERIOR_DERECHO, "System JAADE SAC", "soy un mensaje", Notification.LIGHT_THEME, (short) 2, true, 1500);
  }//GEN-LAST:event_btnTestNotification2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    System.exit(0);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btnTestNotification3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestNotification3ActionPerformed
    Notification.showConfirm(Notification.SUPERIOR_DERECHO, "System JAADE SAC", "soy un mensaje", Notification.BLUE_THEME, (short) 2, true, 1500);
  }//GEN-LAST:event_btnTestNotification3ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TestComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TestComponents().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnTestNotification;
  private javax.swing.JButton btnTestNotification1;
  private javax.swing.JButton btnTestNotification2;
  private javax.swing.JButton btnTestNotification3;
  private javax.swing.JButton jButton1;
  // End of variables declaration//GEN-END:variables
}
